CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');
ALTER TYPE public.account_type OWNER TO cse340af_m1;


-- Table structure for table `classification`
CREATE TABLE public.classification (
  classification_id INT GENERATED BY DEFAULT AS IDENTITY,
  classification_name CHARACTER VARYING NOT NULL,
  CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);


-- Table structure for table `inventory`
CREATE TABLE IF NOT EXISTS public. inventory
(
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	inv_make character varying NOT NULL,
    inv_model character varying NOT NULL,
    inv_year character(4) NOT NULL,
    inv_description text NOT NULL,
    inv_image character varying NOT NULL,
    inv_thumbnail character varying NOT NULL,
    inv_price numeric(9,0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color character varying NOT NULL,
    classification_id integer NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);


-- Create relationship between `classification` and `inventory` tables
ALTER TABLE IF EXISTS public.inventory
  ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
  REFERENCES public.classification (classification_id) MATCH SIMPLE
  ON UPDATE CASCADE
  ON DELETE NO ACTION;


CREATE TABLE IF NOT EXISTS public.account
(
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- Data for table `clasification`
INSERT INTO public.classification (classification_name)
VALUES ('Custom'),
   ('Sport'),
   ('SUV'),
   ('Truck'),
   ('Sedan');

-- Modify the "GM Hummer" record
UPDATE inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- Update all records in inventory
UPDATE inventory
SET
  inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
  inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');

CREATE TABLE message (
  message_id SERIAL PRIMARY KEY,
  message_subject VARCHAR(255) NOT NULL,
  message_body TEXT NOT NULL,
  message_created TIMESTAMPTZ NOT NULL DEFAULT now(),
  message_to INTEGER NOT NULL,
  message_from INTEGER NOT NULL,
  message_read BOOLEAN NOT NULL DEFAULT FALSE,
  message_archived BOOLEAN NOT NULL DEFAULT FALSE,
  FOREIGN KEY (message_to) REFERENCES account(account_id),
  FOREIGN KEY (message_from) REFERENCES account(account_id)
);
